# action.yml
name: 'Probely security scan'
description: 'Scan your application for vulnerabilities with Probely'
inputs:
  api-key:
    description: Probely's API Key
    required: true
  target-id:
    description: Probely's identifier of the target to scan
    required: true
  region:
    description: Probely's region where your account is hosted
    default: "eu"
  scan-profile:
    description: The scan profile to use in the scan. If not defined, the scan profile will be the one defined in the target settings.
    default: ""

runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - "--api-key"
    - ${{ inputs.api-key }}
    - "--target-id"
    - ${{ inputs.target-id }}
    - "--region"
    - ${{ inputs.region }}
    - "--scan-profile"
    - ${{ inputs.scan-profile }}

branding:
  icon: 'chevron-right'
  color: 'blue'
  
